### ISSUE TITLE
Local Keycloak server no longer runs

### ISSUE THREAD

**Issue by paulwaitehomeoffice** [UKHomeOffice/keycloak-theme-govuk#33]
### Steps to reproduce

As per https://github.com/UKHomeOffice/keycloak-theme-govuk#local-keycloak-server:

1. Make sure you’ve installed and started Docker Community Edition
2. `$ npm install`
3. `$ npm run build`
4. `$ docker-compose up`

### Expected behaviour:

The Keycloak server will now be available on http://localhost:8080

### Actual behaviour

The Keycloak server is not available, and we get some errors, possibly about not being able to get a database connection. (Console output from `docker-compose up` attached.)

[docker-compose-error.txt](https://github.com/UKHomeOffice/keycloak-theme-govuk/files/3525313/docker-compose-error.txt)

**Comment by paulwaitehomeoffice** [comment]
Hi @daniel-ac-martin . Does any of the above ring any obvious bells with you? My docker-compose knowledge is a bit limited.

**Comment by paulwaitehomeoffice** [comment]
I notice that our docker-compose file uses [the `links` option](https://docs.docker.com/compose/compose-file/#links), which according to the docs is a legacy feature and may be removed.

The docs don't say it has been removed, but I wonder if it's the cause of the Keycloak service not being able to connect to the Maria DB service.

**Comment by daniel-ac-martin** [comment]
I don't think those lines should do any harm.

**Comment by paulwaitehomeoffice** [comment]
@daniel-ac-martin I agree, although something isn't working any more for some reason. Can you successfully run `docker-compose up` on your computer?
